export const LOADING = "Loading data";
export const ERROR = "Error";
export const LOGIN = "login successfully";
export const SIGNUP = "singup success";
export const LOAD_PROFILE = "loaded profile data";
export const ADD_INCOME = "add income to the list ";
export const DELETE_INCOME = "delete income from the list";
export const UPDATE_INCOME = "update income in the list";
export const LOAD_INCOME = "Income loaded successfully";
export const SORTING='sort data'
export const FILTER='filter data'
export const SORTING_EXPENSE = "sort Expense data";
export const FILTER_EXPENSE = "filter Expense data";
export const ADD_EXPENSE = "add expense";
export const LOAD_EXPENSE = "load expense";
export const ADD_SAVING = "add saving data";
export const LOAD_SAVING = "load saving data";
export const FILTER_SAVING = "filter saving";
export const SORT_SAVING = "sort saving";