export const LOADING = "Loading data";
export const ERROR = "Error";
export const LOGIN = "login successfully";
export const SIGNUP = "singup success";
export const LOAD_PROFILE = "loaded profile data";
export const ADD_INCOME = "add income to the list ";
export const DELETE_INCOME = "delete income from the list";
export const UPDATE_INCOME = "update income in the list";
export const LOAD_INCOME = "Income loaded successfully";
export const SORTING='sort data'
export const FILTER='filter data'